### ISSUE TITLE
Add Allowed Normative Ref - USB IF

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/ag-03#7]
@tbause to add details for this update, including doc types.

**Comment by tbause** [comment]
I asked ST for any objections to add USB-IF to AG-03. No objections were raised during a 2-week period.

**Comment by tbause** [comment]
From: SMPTE Standards Director 
Sent: Thursday, May 2, 2024 4:15 PM
To: ST Standards Committee <st@smpte.org>
Subject: Add USB-IF as allowed normative reference to AG-03

Dear ST Members

As discussed in our most recent ST meeting, I worked with Apple for a while to bring a project to SMPTE which requires normative references to the USB Implementers Forum (USB-IF) specifications. The normative references for the project are below:

•	Universal Serial Bus Type-C Cable and Connector Specification, Release 2.3, Oct 2023
•	Universal Serial Bus Power Delivery Specification, Revision 3.2, Version 1.0, Oct 2023

I am very happy that Apple decided to bring this project to SMPTE and I believe it will broaden SMPTE’s technology portfolio. 

The USB-IF [1] is a non-profit (501(c) (6)) which has rules and IPR policies similar to SMPTE [2][3]. Its specifications are freely and publicly available [4] and the technology is well implemented, stable and under public revision control.

Research showed that USB-IF specifications are used as normative references in documents from other recognized SDOs like ISO.

Please let me know if you have any objections to add USB-IF as an allowed SMPTE normative reference to AG-03 by the 9th of May 2024 CoB (ET). I will file a GitHub issue to update AG-03 if I do not hear any objections by the deadline.

Best Regards
 
Thomas

[1] https://www.usb.org/
[2] https://www.usb.org/about
[3] https://www.usb.org/members
[4] https://www.usb.org/documents

**Comment by palemieux** [comment]
> and IPR policies similar to SMPTE

Is that correct? Where is the IPR policy? At least one [document](https://www.usb.org/document-library/usb-type-cr-cable-and-connector-specification-release-23) states that "In order to obtain any additional intellectual property licenses or licensing commitments associated with the Specification a party must execute the USB 3.0 Adopters Agreement. " This is different than the SMPTE IPR policy which states "Engineering Documents may include technology that is subject to Essential Claims (see section 9.1.2) but only if all known patent holders are prepared to agree to terms that are “Reasonable and Non-Discriminatory” (RAND) for all Essential Claims."

**Comment by palemieux** [comment]
> Research showed that USB-IF specifications are used as normative references in documents from other recognized SDOs like ISO.

Can you provide an example?

**Comment by tbause** [comment]
Are you objecting to adding the USB-IF reference?

ISO/IEC 14776-251:2014(en)
Information technology — Small computer system interface (SCSI) — Part 251: USB attached SCSI (UAS)

**Comment by palemieux** [comment]
> Are you objecting to adding the USB-IF reference?

Yes, because, until proven otherwise, the submission is factually incorrect as far as I can tell regarding the IPR rules being compared to SMPTE's own IPR rules.

**Comment by tbause** [comment]
I am referring to both the USB 2.0 and USB 3.0 Adopters agreements (which covers USB 3.2 as well).

https://www.usb.org/document-library/usb-30-adopters-agreement
https://www.usb.org/document-library/usb-20-specification

These seem to be the applicable ones for the normative references in question.

Regardless of that even the USB 4 Adopters agreement as well as the one you referenced include the provision.

https://www.usb.org/document-library/usb4-adopters-agreement

All are available through the link I provided in my email to ST.

https://www.usb.org/documents

I believe my email to ST which I also copied into the GitHub issue is not factually incorrect as you stated. The IPR policies are similar to those in SMPTE. 

Do you still object to the change to AG-03?

**Comment by tbause** [comment]
The USB Adopters Agreements state ... "Such license shall be granted on a royalty-free basis and under otherwise reasonable and non-discriminatory terms, provided that such license grant may be conditioned upon Licensee’s grant of a reciprocal license binding Licensee."

The documents are publicly available on the USB-IF web-site (see links above)
